/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Old_indexRouteImport } from './routes/old_index'
import { Route as IndexRouteImport } from './routes/index'

const Old_indexRoute = Old_indexRouteImport.update({
  id: '/old_index',
  path: '/old_index',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/old_index': typeof Old_indexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/old_index': typeof Old_indexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/old_index': typeof Old_indexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/old_index'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/old_index'
  id: '__root__' | '/' | '/old_index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Old_indexRoute: typeof Old_indexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/old_index': {
      id: '/old_index'
      path: '/old_index'
      fullPath: '/old_index'
      preLoaderRoute: typeof Old_indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Old_indexRoute: Old_indexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
